# Welcome to Jekyll!

# Website settings
title: Iordanis Thoidis
description: Personal website of Iordanis Thoidis, PhD in Electrical and Computer Engineering
keywords: Hearing Technology, Deep Learning, Speech Processing, Iordanis Thoidis, 
baseurl: /Jalpc
url: https://ithoidis.github.io/Jalpc
img_path: /Jalpc/static/assets/img/blog

# author -- index page "about me" section
author:
  name: Iordanis Thoidis
  first_name: Iordanis
  last_name: Thoidis
  avatar: /static/assets/img/landing/avatar.jpg
  github_username: ithoidis
  linkedin_id: ithoidis
  researchgate_id: Iordanis-Thoidis
  google_scholar_id: FbJnHQEAAAAJ
  email: ithoidis@auth.gr
  cv: https://www.researchgate.net/profile/Iordanis-Thoidis
  skill_icon1:
    - name: fa-microphone
    - name: fa-volume-up
  skill_icon2:
    - name: fa-graduation-cap
    - name: fa-headphones
  desc: |
    I am a Researcher in Hearing Technology, studying how people with hearing loss perceive speech and sound, and developing innovative solutions to make life sound better.

# comment
disqus:
  name: ithoidis

# analytics
ga:
  id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off

## carousels
index_carousel: on
blog_carousel: on

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

