# Welcome to Jekyll!

# Website settings
title: Iordanis Thoidis
description: Personal website of Iordanis Thoidis, PhD in Electrical and Computer Engineering
keywords: Iordanis Thoidis, PhD, Electrical Engineering, Hearing Technology, Deep Learning, Speech Processing
baseurl: /Jalpc
url: https://ithoidis.github.io/Jalpc
img_path: /Jalpc/static/assets/img/blog

# author -- index page "about me" section
author:
  name: Iordanis Thoidis
  first_name: Iordanis
  last_name: Thoidis
  avatar: /static/assets/img/landing/avatar.jpg
  github_username: ithoidis
  linkedin_id: ithoidis
  researchgate_id: Iordanis-Thoidis
  google_scholar_id: FbJnHQEAAAAJ
  email: ithoidis@auth.gr
  cv: https://www.researchgate.net/profile/Iordanis-Thoidis
  skill_icon1:
    - name: fa-graduation-cap
    - name: fa-microphone
    - name: fa-brain
  skill_icon2:
    - name: fa-code
    - name: fa-signal
    - name: fa-hearing
  desc: I am a PhD in Electrical and Computer Engineering from the Aristotle University of Thessaloniki, Greece. My research focuses on hearing technology, aiming to restore speech perception for people with hearing loss in complex acoustic environments. My expertise includes deep learning, speech processing, audio semantic analysis, mobile audiometry, hearing aid design, and auditory modelling.

# comment
disqus:
  name: ithoidis

# analytics
ga:
  id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off

## carousels
index_carousel: on
blog_carousel: on

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

